### ISSUE TITLE
Plugin doesn't work with push plugin

### ISSUE THREAD

**Issue by filoozom** [adcash/cordova-plugin-adcash#2]
This plugin doesn't work with ```phonegap-plugin-push```.
Build error:
```
:dexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzma$zza;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/Users/filoozom/Library/Android/sdk/build-tools/22.0.1/dx --dex --no-optimize --output /Users/filoozom/adcash/platforms/android/build/intermediates/dex/debug --input-list=/Users/filoozom/adcash/platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzma$zza;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)
  	


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by serphen** [comment]
Hello,

Do you have com.google.android.gms:play-services in your build.gradle ? If yes, can you try commenting it ?
Otherwise you may want to try multiDexEnabled true in build.gradle

**Comment by filoozom** [comment]
My build.gradle contains:
```
compile "com.android.support:support-v4:7.5.0"
compile "com.google.android.gms:play-services:7.5.0"
compile "com.android.support:support-v13:23+"
compile "com.google.android.gms:play-services-gcm:+"
```

Does that mean that both plugins rely on different versions of ```com.android.support``` and ```com.google.android.gms```?
I can't find an easy way to remove one of those dependencies with cordova.

**Comment by adoychinov** [comment]
You can read more info here for the same problem: https://github.com/phonegap-build/PushPlugin/issues/492
We use google-play-services and android-support-v4 library and one or both are used in Push plugin too. 
You should remove one of the libraries, because that causes the conflict.

**Comment by filoozom** [comment]
So, after some basic searches in ```src/android/libs/adcash-sdk-lib-1.2.1.jar```, my understanding is that this plugin only uses ```com.google.android.gms:play-services-gcm``` from this list: https://developers.google.com/android/guides/setup#split.

So I replaced:
- ```com.google.android.gms:play-services:7.5.0``` with ```com.google.android.gms:play-services-gcm:+```
- ```com.android.support:support-v4:7.5.0``` with ```com.android.support:support-v13:23+```

which are the same as the ```phonegap-plugin-push``` dependencies and seem to be working. For others having the same problem, you can find my working version here: https://github.com/filoozom/cordova-plugin-adcash/commit/a5c986d2c9372c8d3f8631b7c3f9566a2337e384.

**Comment by serphen** [comment]
Thank you for the patch, we'll review the revision and merge it if it passes our tests
